### ISSUE TITLE
output with Hills shows artifacts on export

### ISSUE THREAD

**Issue by viperscape** [jice-nospam/wgen#2]
When exporting I see artifacts in the png that don't exist in the preview, hiding Hills from the layer stack seems to resolve this. I suspect it's being rendered to disk in a different order.

![image](https://user-images.githubusercontent.com/3178836/221901296-8d53964d-b8e9-4247-bbac-5866f10abcd6.png)

**Comment by jice-nospam** [comment]
Hello, I don't reproduce it. Could you post you project file here so I can use the same parameters as you ?
On a side note, it makes no sense to put LandMass and WaterErosion at the beginning of the stack, they're supposed to modify an existing heightmap. On an empty heightmap, they have no effect.

![image](https://user-images.githubusercontent.com/7805711/222101675-ae84b46e-550d-4b63-abee-f95905408d26.png)

**Comment by viperscape** [comment]
Reloading the project and the output looks fine now, not sure what happened there. Thanks didn't realize I had those at the beginning as I was moving things around and removing steps in the generator, going to close this!
