### ISSUE TITLE
About scale up near to 500 in Godot

### ISSUE THREAD

**Issue by 123ysys** [jice-nospam/wgen#4]
Hello. In read.me introduction you mentioned, with Heightterrain plugin in Godot increase the y scale HTerrain object to something near 500. But if I have other max height number, let's say 2500m, should I still increase the y scale to 500? Or should I scale it to 2500? Thank you.

**Comment by jice-nospam** [comment]
500 is the y scale you should use to have the same look in Godot as in wgen. If you scale even higher, you'll get higher mountains but the map might start to look stretched in the y direction. What you might want to do though is first scale y 500 to get a proper y/xz scale, then scale X5 in all directions. This will get you 2500 height while maintaining the y/xz ratio

**Comment by 123ysys** [comment]
> 500 is the y scale you should use to have the same look in Godot as in wgen. If you scale even higher, you'll get higher mountains but the map might start to look stretched in the y direction. What you might want to do though is first scale y 500 to get a proper y/xz scale, then scale X5 in all directions. This will get you 2500 height while maintaining the y/xz ratio

Thank you. I see.
